export const refs = {
  queueEl: document.querySelector('.header-btn__queue'),
  watchedEl: document.querySelector('.header-btn__watched'),
  loadMoreBtnEl: document.querySelector('.load-more-btn'),
  bodyEl: document.querySelector('body'),
  backdropEl: document.querySelector('.backdrop'),
  buttonCloseEl: document.querySelector('.modal__button'),
  bodyNoScrollEl: document.querySelector('[data-nonScroll]'),
  filmCardLinkEl: document.querySelector('.film-card__link'),
  filmsGalleryEl: document.querySelector('.films-gallery'),
  footerBtn: document.querySelector('.footer__btn'),
  modalCardEl: document.querySelector('.modal-card'),
  libraryEl: document.querySelector('.library-gallery'),
  modalCardImg: document.querySelector('.modal-card__img'),
  modalSpinnerEl: document.querySelector('.modal-spinner'),
  scrollBtnEl: document.querySelector('.arrow-up'),
};
